version: "3.9"

services:
  db:
    extends:
      file: ./docker/db.yml
      service: db
  web:
    extends:
      file: ./docker/web.yml
      service: web
    depends_on:
      - db
  webserver:
    extends:
      file: ./docker/webserver.yml
      service: webserver
    depends_on:
      - web
volumes:
  static-data:
  db-data: