version: "3.9"

services:
  db:
    extends:
      file: ./docker/db.yml
      service: db
    depends_on:
      - web
  web:
    extends:
      file: ./docker/web.yml
      service: web
volumes:
  db-data: