version: "3.9"

services:
  db:
    extends:
      file: ./docker/db.yml
      service: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    depends_on:
      - web
  web:
    extends:
      file: ./docker/web.yml
      service: web
    entrypoint: ["/data/web_start.dev.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./data/web_start.dev.sh:/data/web_start.dev.sh
      - ./static:/public/static
